language: node_js
node_js:
  - "12"
dist: bionic

before_script:
  - npm install

matrix:
  include:
    - name: build
      script:
        - npm run dist
        - git diff --exit-code
    - name: test
      script:
        - npm run test
    - name: fmt
      script:
        - npm run fmt
        - git diff --exit-code
