language: node_js
node_js:
  - "12"
dist: bionic

matrix:
  include:
    - name: build
      script:
        - npm install
        - npm run build
        - git diff --exit-code
    - name: test
      script:
        - npm install
        - npm run test
